export const state = {
  vendas: [],
  vendaEmEdicaoId: null,
  vendaOriginalRegistradoPor: null,
  vendaOriginalRegistradoPorId: null,
  vendaOriginalTimestamp: null,
  vendaOriginalDataHora: null,
  vendaOriginalDossierOrg: null,
  vendaOriginalCliente: null,
  vendaOriginalOrganizacao: null,
  currentUser: null,
  currentUserData: null,
  globalOnlineStatus: {},
  globalAllOrgs: [],
  globalCurrentPeople: [],
  sortableInstance: null,
  orgSortableInstance: null,
  tempVeiculos: {},
  veiculoEmEdicaoKey: null,
  vendasListener: null,
};
